version: "3.9"
services:
    nginx:
        image: "nginx:alpine"
        restart: always
        working_dir: /app
        links:
            - php-fpm
        volumes:
            - ".:/app"
            - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "8099:80"

    php-fpm:
        build:
            context: ./docker/php-fpm
        restart: always
        working_dir: /app
        links:
            - redis
        volumes:
            - ".:/app"
    composer:
        restart: 'no'
        image: composer/composer
        command: install
        volumes:
            - .:/app
    redis:
        image: redis:4.0
        ports:
            - "6379:6379"

